#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.appdb-env.sh ] && source ~/.appdb-env.sh

if command -v "jump" >/dev/null 2>&1; then
  eval "$(jump shell zsh)"
fi

if command -v "hub" >/dev/null 2>&1; then
  alias git=hub
fi

# TODO check that vboxmanage completion is available
# /usr/share/zsh/site-functions/_virtualbox
if type compdef &>/dev/null; then
  if type VBoxManage &>/dev/null; then
    compdef vboxmanage=VBoxManage
    compdef vboxheadless=VBoxHeadless
  fi
fi
